name: build

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: '48 20 * * 4'

jobs:
  build-example:
    name: build example project
    runs-on: ubuntu-latest
    container: ghcr.io/cirruslabs/flutter:stable

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        working-directory: example/example_werkbank
        run: flutter pub get

      - name: Build web version of the example project
        working-directory: example/example_werkbank
        run: flutter build web --base-href /werkbank/

      - name: Upload the generated artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: example/example_werkbank/build/web
          retention-days: 90

  deploy-example:
    name: deploy example project
    runs-on: ubuntu-latest
    needs: build-example

    if: ${{ github.ref == 'refs/heads/main' && vars.DEPLOY_PAGES }}

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4


