name: build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-example:
    name: build example project
    runs-on: ubuntu-latest
    container: ghcr.io/cirruslabs/flutter:3.32.2

    steps:
      - uses: actions/checkout@v4

      - name: Check expected flutter version
        shell: python3 {0}
        run: |
          import json

          fvmrc_version = json.load(open(".fvmrc"))["flutter"]
          sdk_version = open("/sdks/flutter/version").read().strip()

          assert fvmrc_version == sdk_version

      - name: Install dependencies
        working-directory: example/example_werkbank
        run: flutter pub get

      - name: Build web version of the example project
        working-directory: example/example_werkbank
        run: flutter build web --base-href /werkbank/

      - name: Upload the generated artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: example/example_werkbank/build/web
          retention-days: 90
