name: test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        directory:
          - "example/example_werkbank"
          - "packages/werkbank"

    name: flutter test
    runs-on: ubuntu-latest
    container: ghcr.io/cirruslabs/flutter:stable

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        working-directory: ${{ matrix.directory }}
        run: flutter pub get

      - name: Run Unit Tests
        working-directory: ${{ matrix.directory }}
        run: flutter test
